# Generated by Django 2.1.4 on 2019-09-02 00:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190831_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='editors',
            field=models.ManyToManyField(related_name='editors', to=settings.AUTH_USER_MODEL),
        ),
    ]
